### ISSUE TITLE
Hey, its not issue..

### ISSUE THREAD

**Issue by thapakazi** [jwiegley/notes#1]
I was wondering if you would share how you generate this repo from your gist pool. :neckbeard: 

![happy_keed_playing_with_water](https://cloud.githubusercontent.com/assets/1695906/13945745/dc93ac56-f037-11e5-8f0a-8a812ddc3642.gif)

no worries if you haven't time to address this thread 
thanks

**Comment by jwiegley** [comment]
Sure, there's a file in this repository called `gist-backup.py`.  Not all of it is from gists, though, most of them I just write by hand as needed.

**Comment by thapakazi** [comment]
Thank you for this py script. @jwiegley :feelsgood:
